# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: draw.sh

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pandas
        pip install matplotlib==3.3.4
    - name: Update bilibili
      run: sh draw.sh
      
    - name: Commit
      run: |
        git config --global user.email 185429663@qq.com
        git config --global user.name Graysonnwu
        git add .
        #git commit -m"action:`date +'%Y-%m-%d'`"
        git commit -m"action:`date`"
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
